INSERT INTO CURRENCY_EXCHANGE VALUES(1, 2, 'USD', 'CLP');
INSERT INTO CURRENCY_EXCHANGE VALUES(2, 1.5, 'USD', 'EUR');
INSERT INTO CURRENCY_EXCHANGE VALUES(3, 0.01, 'USD', 'VES');
INSERT INTO CURRENCY_EXCHANGE VALUES(4, 1.2, 'USD', 'INR');